//! Universal instruction metadata.

use super::*;

impl EmirOp {
    #[must_use]
    pub const fn name(&self) -> &'static str {
        match self {
            Self::ConstF64(_) => "const-f64",
            Self::ConstI64(_) => "const-i64",
            Self::ConstBigInt(_) => "const-bigint",
            Self::ConstText(_) => "const-text",
            Self::ConstComplex(_, _) => "const-complex",
            Self::ConstBool(_) => "const-bool",
            Self::LoadInput(_) => "load-input",
            Self::LoadState(_) => "load-state",
            Self::F64Add(_, _) => "scalar-add",
            Self::F64Sub(_, _) => "scalar-sub",
            Self::F64Mul(_, _) => "scalar-mul",
            Self::F64Div(_, _) => "scalar-div",
            Self::F64Pow(_, _) => "scalar-power",
            Self::Neg(_) => "scalar-negate",
            Self::ToInt(_) => "to-int",
            Self::ToF64(_) => "to-f64",
            Self::IntegerQuotient(_, _) => "integer-quotient",
            Self::SameBits(_, _) => "same-bits",
            Self::UnaryBuiltin(_, _) => "scalar-unary-kernel",
            Self::BinaryBuiltin(_, _, _) => "scalar-binary-kernel",
            Self::Lt(_, _) => "compare-lt",
            Self::Le(_, _) => "compare-le",
            Self::Gt(_, _) => "compare-gt",
            Self::Ge(_, _) => "compare-ge",
            Self::Eq(_, _) => "compare-eq",
            Self::Ne(_, _) => "compare-ne",
            Self::And(_, _) => "boolean-and",
            Self::Or(_, _) => "boolean-or",
            Self::Imply(_, _) => "boolean-imply",
            Self::Iff(_, _) => "boolean-iff",
            Self::Not(_) => "boolean-not",
            Self::IsFinite(_) => "is-finite",
            Self::Select { .. } => "select",
            Self::FormatText { .. } => "format-text",
            Self::SeriesCreate { .. } => "series-create",
            Self::SeriesSample { .. } => "series-sample",
            Self::SetCreate { .. } => "set-create",
            Self::SetContains { .. } => "set-contains",
            Self::RecordCreate { .. } => "record-create",
            Self::ListCreate(_) => "list-create",
            Self::RecordField { .. } => "record-field",
            Self::Branch { .. } => "branch",
            Self::Iterate { .. } => "iterate",
            Self::Refuse(_) => "refuse",
            Self::RefuseValue(_) => "refuse-value",
            Self::VectorCreate(_) => "vector-create",
            Self::VectorLength(_) => "vector-length",
            Self::ToF64Vector(_) => "to-f64-vector",
            Self::MatrixCreate { .. } => "matrix-create",
            Self::TensorCreate { .. } => "tensor-create",
            Self::VectorIndex { .. } => "vector-index",
            Self::MatrixRows(_) => "matrix-rows",
            Self::TensorShape(_) => "tensor-shape",
            Self::F64Exp2(_) => "f64-exp2",
            Self::F64PowI(..) => "f64-powi",
            Self::TextTrim(_) => "text-trim",
            Self::TextLength(_) => "text-length",
            Self::IndexText(_) => "index-text",
            Self::TextByte(..) => "text-byte",
            Self::FormatScientific(..) => "format-scientific",
            Self::ParseF64(_) => "parse-f64",
            Self::TensorPack { .. } => "tensor-pack",
            Self::DenseIndex { .. } => "dense-index",
            Self::MatrixCols(_) => "matrix-cols",
            Self::MatrixPack { .. } => "matrix-pack",
            Self::MatrixIndex { .. } => "matrix-index",
            Self::TensorIndex { .. } => "tensor-index",
            Self::TensorSlice { .. } => "tensor-slice",
            Self::OptionSome(_) => "option-some",
            Self::OptionNone => "option-none",
            Self::OptionIsSome(_) => "option-is-some",
            Self::OptionUnwrapOr(_, _) => "option-unwrap-or",
            Self::ResultOk(_) => "result-ok",
            Self::ResultErr(_) => "result-err",
            Self::ResultIsOk(_) => "result-is-ok",
            Self::ResultUnwrapOr(_, _) => "result-unwrap-or",
            Self::ResultErrorOf(_) => "result-error-of",
            Self::Collect { .. } => "collect",
            Self::Fold { .. } => "fold",
            Self::ApplyCapability { .. } => "apply-capability",
            Self::CallFrame { .. } => "call-frame",
            Self::CallSelf { .. } => "call-self",
            Self::SameDenseShape(..) => "same-dense-shape",
            Self::DenseLayout(_) => "dense-layout",
            Self::VectorSlice { .. } => "vector-slice",
            Self::VectorConcat(_) => "vector-concat",
            Self::F64SortTotal(_) => "f64-sort-total",
            Self::DenseValues(_) => "dense-values",
            Self::DenseRepack { .. } => "dense-repack",
            Self::ProgramLiteral { .. } => "program-literal",
            Self::CallProgram { .. } => "call-program",
            Self::CallScalarProgram { .. } => "call-scalar-program",
            Self::CallRealProgram { .. } => "call-real-program",
            Self::TryCallRealProgram { .. } => "try-call-real-program",
            Self::VectorMap { .. } => "vector-map",
            Self::VectorMapScalar { .. } => "vector-map-scalar",
            Self::VectorReduce { .. } => "vector-reduce",
            Self::VectorAllFinite(_) => "vector-all-finite",
        }
    }

    #[must_use]
    pub fn format_ssa(&self) -> String {
        if let Self::ApplyCapability { capability, class, args } = self {
            format!("apply-capability name={capability} class={class:?} args={args:?}")
        } else {
            format!("{} {self:?}", self.name())
        }
    }
}
