//! Rust type/naming helpers for the backend.

use super::*;

impl BackendInput<'_> {
    #[must_use]
    pub(super) fn cargo_manifest(&self) -> String {
        format!(
            "# Generated by emath (deterministic; do not edit).\n\
             [package]\n\
             name = \"{}\"\n\
             version = \"{}\"\n\
             edition = \"2024\"\n\
             description = \"Generated from an .emath declaration (strict-f64 native).\"\n\
             license = \"MIT OR Apache-2.0\"\n\
             \n\
             [workspace]\n\
             \n\
             [lib]\n\
             path = \"src/lib.rs\"\n\
             \n\
             [dependencies]\n",
            sanitize_crate_name(&self.crate_name),
            sanitize_version(&self.version)
        )
    }

    pub(super) fn rust_ty(&self, ty: TypeId, owner: &str) -> Result<Ty, BackendError> {
        let Some(node) = self.package.ty(ty) else {
            return Err(BackendError::UnsupportedType(format!(
                "unknown type id in `{owner}`"
            )));
        };
        self.rust_node(node, owner)
    }

    pub(super) fn rust_node(&self, node: &TypeNode, owner: &str) -> Result<Ty, BackendError> {
        match node {
            TypeNode::Float64 => Ok(Ty::F64),
            TypeNode::Bool => Ok(Ty::Bool),
            // Stage-2 (emath-t63iz): the exact big field-element type maps
            // onto the embedded runtime's UBig (verbatim SOURCE module).
            TypeNode::BigInt => Ok(Ty::Named("emath_rt::UBig".to_string())),
            TypeNode::Vector { element, .. } => match element.as_ref() {
                // Nested vectors map onto the row-major matrix runtime
                // representation (Vector<Vector<Float64>> values ARE
                // Vec<Vec<f64>>); deeper nesting has no Phase 1 runtime
                // value and refuses with guidance toward Tensor.
                TypeNode::Vector { element: inner, .. } => {
                    if matches!(**inner, TypeNode::Vector { .. }) {
                        Err(BackendError::UnsupportedType(
                            "nested vectors deeper than two levels have no Phase 1 runtime value; use Tensor<T>".to_string(),
                        ))
                    } else {
                        Ok(Ty::Named("Vec<Vec<f64>>".to_string()))
                    }
                }
                TypeNode::BigInt => Ok(Ty::Named("Vec<emath_rt::UBig>".to_string())),
                _ => Ok(Ty::Named("Vec<f64>".to_string())),
            },
            TypeNode::Matrix { .. } => Ok(Ty::Named("Vec<Vec<f64>>".to_string())),
            TypeNode::Tensor { .. } => Ok(Ty::Named("emath_rt::Tensor".to_string())),
            TypeNode::Nat | TypeNode::Int => Ok(Ty::I64),
            TypeNode::Refinement { base, .. } => self.rust_node(base, owner),
            TypeNode::UnitRef { .. } => Ok(Ty::F64),
            TypeNode::Opaque { name, .. } => {
                let leaf = name.leaf();
                if leaf.is_empty() {
                    Err(BackendError::UnsupportedType(format!(
                        "anonymous host type in `{owner}`"
                    )))
                } else {
                    Ok(Ty::Named(escape_ident(leaf)))
                }
            }
            other => Err(BackendError::UnsupportedType(format!(
                "`{}` in `{owner}`",
                other.display_name()
            ))),
        }
    }

    /// Rust type for an OUTPUT field. Unlike `rust_node` (which refuses
    /// carrier types — see `carrier_field_decl_refuses_typed`, the input
    /// boundary), outputs may NAME a carrier: a declaration returning an
    /// `Option<T>`/`Result<T,E>` field maps to the native Rust carrier
    /// type (`Option<i64>`, `Option<Option<i64>>`, …). The runtime value
    /// is emitted by `op_expr`; only the signature type differs. Recurses
    /// for nested carriers.
    pub(super) fn rust_output_ty(&self, ty: TypeId, owner: &str) -> Result<Ty, BackendError> {
        let Some(node) = self.package.ty(ty) else {
            return Err(BackendError::UnsupportedType(format!(
                "unknown type id in `{owner}`"
            )));
        };
        self.rust_output_node(node, owner)
    }

    pub(super) fn rust_output_node(
        &self,
        node: &TypeNode,
        owner: &str,
    ) -> Result<Ty, BackendError> {
        match node {
            TypeNode::OptionType(inner) => Ok(Ty::Named(format!(
                "Option<{}>",
                render_ty(&self.rust_output_node(inner, owner)?)
            ))),
            TypeNode::Result { ok, error } => Ok(Ty::Named(format!(
                "Result<{}, {}>",
                render_ty(&self.rust_output_node(ok, owner)?),
                render_ty(&self.rust_output_node(error, owner)?)
            ))),
            other => self.rust_node(other, owner),
        }
    }

    pub(super) fn error_type_name(&self, error_type: Option<TypeId>) -> &str {
        let Some(ty) = error_type.and_then(|id| self.package.ty(id)) else {
            return DEFAULT_ERROR_TYPE;
        };
        if let TypeNode::Other(name) = ty {
            if !name.leaf().is_empty() && name.leaf() != "Self" {
                return "ConfigError";
            }
        }
        DEFAULT_ERROR_TYPE
    }
}
