[package]
name = "emath-exec-ir"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
emath-core = { workspace = true }
emath-ir = { workspace = true }
emath-rt = { workspace = true }
emath-term = { workspace = true }
emath-artifact = { workspace = true }
emath-schema = { workspace = true }

[lints]
workspace = true
