[package]
name = "emath-store-tests"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
emath-core = { path = "../../crates/emath-core" }
emath-ir = { path = "../../crates/emath-ir" }
emath-sema = { path = "../../crates/emath-sema" }
emath-store = { path = "../../crates/emath-store" }
emath-syntax = { path = "../../crates/emath-syntax" }
