//! World codegen model: specs, refusals, package generation.

use super::*;

/// Version of the generated world ABI surface (generic + specialized traits
/// and dispatcher); every generated crate embeds it so consumers can pin the
/// ABI they compiled against.
pub const WORLD_ABI_VERSION: u32 = 1;

/// A world whose implementation is generated.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WorldSpec {
    /// Stable label: `free_symbolic`, `boolean_algebra`, or `modular_numeric`.
    pub label: String,
    /// Declared operator semantics actually interpreted by the genesis
    /// analysis; meanings codegen does not hardcode are refused `E-GEN-094`.
    pub operators: Vec<(String, String)>,
}

/// Typed refusal for codegen inputs outside the label-based subset.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CodegenRefusal {
    /// Stable diagnostic code (`E-GEN-094`).
    pub code: &'static str,
    /// Human-readable refusal.
    pub message: String,
}

/// The fixed operator semantics the label-based emission hardcodes.
/// These must stay in lockstep with the generated world `apply`
/// implementations inside `LIB_TEMPLATE`.
pub(super) fn default_operator_semantics(label: &str) -> &'static [(&'static str, &'static str)] {
    match label {
        // `free_symbolic` interprets every operator structurally (no
        // hardcoded meaning), so its declared map must be empty.
        "boolean_algebra" => &[("ζ", "true"), ("⋈", "xor"), ("⧖", "not"), ("⊛", "and")],
        "modular_numeric" => &[
            ("ζ", "3"),
            ("⋈", "(x+y) mod 17"),
            ("⧖", "(x*x) mod 17"),
            ("⊛", "(x*y) mod 17"),
        ],
        _ => &[],
    }
}

/// Deterministic generated package.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedPackage {
    /// Crate name.
    pub crate_name: String,
    /// Relative path → file content.
    pub files: BTreeMap<String, String>,
}

impl GeneratedPackage {
    /// Writes every file under `dir`, replacing existing files.
    pub fn write_to(&self, dir: &Path) -> std::io::Result<()> {
        std::fs::create_dir_all(dir)?;
        for (relative, body) in &self.files {
            let target = dir.join(relative);
            if let Some(parent) = target.parent() {
                std::fs::create_dir_all(parent)?;
            }
            std::fs::write(target, body)?;
        }
        Ok(())
    }
}

/// Emits the parametric crate for `term` under `signature`; refuses
/// (`E-GEN-094`) worlds whose declared operator semantics differ from the
/// hardcoded per-label interpretation (a silent drop would violate SURF-0008).
pub fn generate(
    term: &Term,
    signature: &Signature,
    worlds: &[WorldSpec],
) -> Result<GeneratedPackage, CodegenRefusal> {
    for world in worlds {
        let mut expected = default_operator_semantics(&world.label)
            .iter()
            .map(|&(symbol, meaning)| (symbol.to_string(), meaning.to_string()))
            .collect::<Vec<_>>();
        expected.sort();
        let mut declared = world.operators.clone();
        declared.sort();
        if declared != expected {
            let first = declared
                .iter()
                .find(|probe| !expected.contains(probe))
                .map_or_else(
                    || "extra/missing operator".to_string(),
                    |(symbol, meaning)| format!("`{symbol}` = `{meaning}`"),
                );
            return Err(CodegenRefusal {
                code: "E-GEN-094",
                message: format!(
                    "world `{}` declares operator semantics codegen cannot honor ({first}); \
                     label-based emission hardcodes a fixed interpretation (SURF-0008), so the \
                     unused WorldIr is refused instead of silently dropped",
                    world.label
                ),
            });
        }
    }
    let labels = worlds
        .iter()
        .map(|spec| spec.label.clone())
        .collect::<Vec<_>>();
    let mut files = BTreeMap::new();
    files.insert("Cargo.toml".into(), render_manifest());
    files.insert("src/lib.rs".into(), render_lib(term, signature, &labels));
    files.insert("src/main.rs".into(), render_main(&labels));
    Ok(GeneratedPackage {
        crate_name: "semantic-genesis-worlds".into(),
        files,
    })
}

pub(super) fn render_manifest() -> String {
    r#"# Generated by emath Semantic Genesis (deterministic; do not edit).
[package]
name = "semantic-genesis-worlds"
version = "0.1.0"
edition = "2024"
description = "Generated parametric worlds for the reference alien signature."
license = "Apache-2.0"

[lib]
path = "src/lib.rs"

[[bin]]
name = "semantic-genesis-worlds"
path = "src/main.rs"

[dependencies]
"#
    .to_string()
}
