[package]
name = "emath-lab-core"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
emath-ir = { path = "../emath-ir" }
emath-world-ir = { path = "../emath-world-ir" }
emath-term = { path = "../emath-term" }
emath-core = { workspace = true }

[lints]
workspace = true
