//! Tooling commands: `new`, `fmt`, `explain`, `run`, `test`, `bench`,
//! `verify`, `inspect`, `diff`, `doctor`, `vendor`, `provider`, `fork`,
//! and the structured `agent` API envelope.
//!
//! Implemented commands exercise the real pipeline (check/plan/build,
//! artifact verification). Capabilities outside the Phase 1 subset are
//! typed refusals with stable codes (`E-TLT-*`, `E-PROV-*`); nothing is
//! silently accepted.

use std::path::{Path, PathBuf};
use std::process::Command;

use emath_artifact::JsonWriter;
use emath_build::{build_file, BuildOptions};
use emath_core::content_id_of_str;
use emath_sema::session::CompilerSession;

use crate::{artifact_check, print_diagnostics, EXIT_OK, EXIT_REFUSED, EXIT_USAGE};

/// Relative path of the committed upstream lock file (repo layout).
const UPSTREAM_LOCK_REL: &str = "forks/UPSTREAM_LOCK.json";

/// Absolute lock path: crate-relative so `vendor`/`fork` work regardless of
/// the caller's working directory.
fn upstream_lock_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join(UPSTREAM_LOCK_REL)
}

/// Built-in provider descriptors: (id, capability, status).
const PROVIDERS: [(&str, &str, &str); 6] = [
    (
        "native.rust",
        "scalar codegen + checked constructors",
        "implemented",
    ),
    (
        "evidence.rust",
        "artifact verification + negative controls",
        "implemented",
    ),
    (
        "phase2.expression",
        "expression optimization / codegen",
        "planned",
    ),
    (
        "phase3.structural",
        "equations, flattening, DAE analysis",
        "planned",
    ),
    ("phase4.symbolic", "differential oracle", "planned"),
    ("phase5.numerics", "solvers and optimization", "planned"),
];

/// Dispatch for all tooling subcommands added by the tooling slice.
pub fn tooling_dispatch(command: &str, args: &[String]) -> u8 {
    match command {
        "new" => new_cmd(args),
        "fmt" => fmt_cmd(args),
        "explain" => explain_cmd(args),
        "run" => run_cmd(args),
        "test" => test_cmd(args),
        "bench" => bench_cmd(args),
        "verify" => verify_cmd(args),
        "inspect" => inspect_cmd(args),
        "diff" => diff_cmd(args),
        "doctor" => doctor_cmd(args),
        "vendor" => vendor_cmd(args),
        "provider" => provider_cmd(args),
        "fork" => fork_cmd(args),
        "agent" => agent_cmd(args),
        _ => EXIT_USAGE,
    }
}

/// `new <name> --out <dir>`: deterministic project scaffold.
fn new_cmd(args: &[String]) -> u8 {
    let Some(name) = args.first() else {
        return usage("new <name> --out <dir>");
    };
    if !is_valid_name(name) {
        eprintln!("error: invalid package name `{name}` (E-TLT-010)");
        return EXIT_USAGE;
    }
    let Some(out) = flag_value("--out", args).or_else(|| flag_value("-o", args)) else {
        return usage("new <name> --out <dir>");
    };
    let out = PathBuf::from(out);
    let main = out.join("src/main.emath");
    let manifest = out.join("emath-package.toml");
    if main.exists() || manifest.exists() {
        eprintln!(
            "error: refusing to overwrite existing project at {} (E-TLT-011)",
            out.display()
        );
        return EXIT_REFUSED;
    }
    if std::fs::create_dir_all(out.join("src")).is_err() {
        eprintln!("error: cannot create {}", out.display());
        return EXIT_USAGE;
    }
    let manifest_body = format!(
        "# Generated by emath new (deterministic template; edit freely).\nschema = \"emath.package.v1\"\nname = \"{name}\"\nversion = \"0.1.0\"\nedition = \"0.1\"\nmain = \"src/main.emath\"\n",
    );
    let main_body = "emath function Greeter:\n    inputs:\n        x: Float64\n    outputs:\n        y: Float64\n    definitions:\n        y = x\n";
    let result =
        std::fs::write(&manifest, &manifest_body).and_then(|()| std::fs::write(&main, main_body));
    if result.is_err() {
        eprintln!("error: cannot write scaffold under {}", out.display());
        return EXIT_USAGE;
    }
    println!(
        "created {} (content id {})",
        manifest.display(),
        content_id_of_str(&manifest_body).0
    );
    println!(
        "created {} (content id {})",
        main.display(),
        content_id_of_str(main_body).0
    );
    println!("next: emath check {} --json", main.display());
    EXIT_OK
}

fn is_valid_name(name: &str) -> bool {
    let mut chars = name.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    first.is_ascii_alphabetic()
        && chars.all(|ch| ch.is_ascii_alphanumeric() || ch == '_' || ch == '-')
}

/// `fmt <file>`: canonical-form check via the real lossless formatter.
/// The file is canonical only when the formatter round-trips it byte for
/// byte; anything less is a refusal with a diff preview, never a fake ok.
fn fmt_cmd(args: &[String]) -> u8 {
    let Some(file) = first_positional(args) else {
        return usage("fmt <file.emath>");
    };
    let mut session = CompilerSession::new(emath_core::limits::Limits::default());
    let Ok(package) = session.load_package(&file) else {
        eprintln!("error: cannot read {file}");
        return EXIT_USAGE;
    };
    let result = session.check(package.file);
    print_diagnostics(&result.diagnostics);
    if result.diagnostics.has_errors() {
        return EXIT_REFUSED;
    }
    let limits = emath_core::limits::Limits::default();
    let lossless = emath_syntax::parse_lossless(&package.text, package.file, &limits);
    let canonical = emath_syntax::formatter::format(&lossless.tree, &lossless.comments);
    if canonical == package.text {
        println!("fmt: {file}: canonical form (lossless round-trip)");
        EXIT_OK
    } else {
        eprintln!("fmt: {file}: NOT canonical; expected lossless formatter output");
        for (line_no, (expected, actual)) in canonical
            .lines()
            .zip(package.text.lines())
            .enumerate()
            .filter(|(_, (expected, actual))| expected != actual)
            .take(10)
        {
            eprintln!(
                "  line {}: expected `{expected}`, found `{actual}`",
                line_no + 1
            );
        }
        EXIT_REFUSED
    }
}

/// `explain <file> [<symbol>]`: plan-level explanation of goals.
fn explain_cmd(args: &[String]) -> u8 {
    let Some(file) = first_positional(args) else {
        return usage("explain <file.emath> [<symbol>]");
    };
    let symbol = args
        .iter()
        .filter(|arg| !arg.starts_with('-'))
        .nth(1)
        .cloned();
    let mut session = CompilerSession::new(emath_core::limits::Limits::default());
    let Ok(package) = session.load_package(&file) else {
        eprintln!("error: cannot read {file}");
        return EXIT_USAGE;
    };
    let result = session.plan(package.file);
    print_diagnostics(&result.diagnostics);
    if result.diagnostics.has_errors() {
        return EXIT_REFUSED;
    }
    for goal in &result.package.goals {
        println!(
            "explain: goal `{} {}` -> deterministic native plan",
            goal.kind.as_str(),
            goal.target
        );
    }
    for plan in &result.plans {
        println!(
            "explain: plan {} policy={} class={}",
            plan.plan_id.0, plan.policy, plan.artifact_class
        );
    }
    if let Some(symbol) = symbol {
        println!(
            "explain: symbol `{symbol}`: declaration indexing is Phase 4+; goals above are the available evidence"
        );
    }
    EXIT_OK
}

/// `run <file> --out <dir>`: build then execute the generated crate.
fn run_cmd(args: &[String]) -> u8 {
    let Some(file) = first_positional(args) else {
        return usage("run <file.emath> --out <dir>");
    };
    let Some(out) = flag_value("--out", args).or_else(|| flag_value("-o", args)) else {
        return usage("run <file.emath> --out <dir>");
    };
    let out = PathBuf::from(out);
    let report = match build_file(
        &file,
        &out,
        BuildOptions {
            verify_generated_crate: false,
        },
    ) {
        Ok(report) => report,
        Err(error) => {
            eprintln!("error: {error}");
            return classify_build_error(&error);
        }
    };
    let manifest = report.artifact_dir.join("Cargo.toml");
    let mut command = Command::new("cargo");
    command
        .args(["run", "--quiet", "--manifest-path"])
        .arg(&manifest);
    let output = match command.output() {
        Ok(output) => output,
        Err(error) => {
            eprintln!("error: cannot execute generated crate: {error}");
            return EXIT_USAGE;
        }
    };
    print!("{}", String::from_utf8_lossy(&output.stdout));
    eprint!("{}", String::from_utf8_lossy(&output.stderr));
    if output.status.success() {
        EXIT_OK
    } else {
        eprintln!("error: generated crate exited with {}", output.status);
        EXIT_REFUSED
    }
}

/// `test <file> --out <dir>`: build and run the generated crate's tests.
fn test_cmd(args: &[String]) -> u8 {
    let Some(file) = first_positional(args) else {
        return usage("test <file.emath> --out <dir>");
    };
    let Some(out) = flag_value("--out", args).or_else(|| flag_value("-o", args)) else {
        return usage("test <file.emath> --out <dir>");
    };
    match build_file(
        &file,
        PathBuf::from(out),
        BuildOptions {
            verify_generated_crate: true,
        },
    ) {
        Ok(report) => {
            println!(
                "test: artifact {} crate `{}` tests passed",
                report.artifact_id.0, report.crate_name
            );
            EXIT_OK
        }
        Err(error) => {
            eprintln!("error: {error}");
            classify_build_error(&error)
        }
    }
}

/// `bench <file>`: typed refusal (benchmark harness is Phase 4+).
fn bench_cmd(args: &[String]) -> u8 {
    let Some(file) = first_positional(args) else {
        return usage("bench <file.emath>");
    };
    eprintln!(
        "error: E-TLT-004: benchmarking `{file}` requires the Phase 4+ benchmark harness (emath-lab-core scaffold exists)"
    );
    EXIT_REFUSED
}

/// `verify <dir>`: independent artifact re-verification.
fn verify_cmd(args: &[String]) -> u8 {
    let Some(dir) = first_positional(args) else {
        return usage("verify <artifact-dir>");
    };
    artifact_check(&PathBuf::from(dir))
}

/// `inspect <dir>`: print the committed artifact manifest. Reads exactly
/// the file `emath build` writes (`<dir>/emath/<id>/emath/artifact-manifest.json`)
/// and refuses non-UTF-8 manifests instead of substituting lossy text
fn inspect_cmd(args: &[String]) -> u8 {
    let Some(dir) = first_positional(args) else {
        return usage("inspect <artifact-dir>");
    };
    let dir = PathBuf::from(dir);
    let root = dir.join("emath");
    let Ok(entries) = std::fs::read_dir(&root) else {
        eprintln!(
            "error: E-TLT-005: no `emath/` state directory under {}",
            dir.display()
        );
        return EXIT_USAGE;
    };
    let mut inspected = 0;
    for entry in entries.flatten() {
        if !entry.path().is_dir() {
            continue;
        }
        let manifest = entry.path().join("emath/artifact-manifest.json");
        let bytes = match std::fs::read(&manifest) {
            Ok(bytes) => bytes,
            Err(error) => {
                eprintln!(
                    "error: E-TLT-005: cannot read manifest at {}: {error}",
                    manifest.display()
                );
                return EXIT_REFUSED;
            }
        };
        let Ok(text) = String::from_utf8(bytes) else {
            eprintln!(
                "error: E-EVID-114: manifest is not valid UTF-8 at {}",
                manifest.display()
            );
            return EXIT_REFUSED;
        };
        println!("artifact {}:", entry.file_name().to_string_lossy());
        println!("{text}");
        inspected += 1;
    }
    if inspected == 0 {
        eprintln!("error: E-TLT-005: no artifacts under {}", root.display());
        EXIT_USAGE
    } else {
        EXIT_OK
    }
}

/// `diff <a.emath> <b.emath>`: fingerprint comparison of parse-admitted sources.
fn diff_cmd(args: &[String]) -> u8 {
    let positional = positional_args(args);
    let Some(a) = positional.first() else {
        return usage("diff <a.emath> <b.emath>");
    };
    let Some(b) = positional.get(1) else {
        return usage("diff <a.emath> <b.emath>");
    };
    let id_a = fingerprint(a);
    let id_b = fingerprint(b);
    match (id_a, id_b) {
        (Ok(id_a), Ok(id_b)) => {
            println!("diff: {a} {}", id_a.0);
            println!("diff: {b} {}", id_b.0);
            if id_a == id_b {
                println!("diff: identical");
                EXIT_OK
            } else {
                println!("diff: differ");
                EXIT_REFUSED
            }
        }
        (Err(()), _) | (_, Err(())) => EXIT_REFUSED,
    }
}

/// Content id of a parse-admitted source; diagnostics printed on refusal.
fn fingerprint(file: &str) -> Result<emath_core::ContentId, ()> {
    let mut session = CompilerSession::new(emath_core::limits::Limits::default());
    let Ok(package) = session.load_package(file) else {
        eprintln!("error: cannot read {file}");
        return Err(());
    };
    let result = session.check(package.file);
    print_diagnostics(&result.diagnostics);
    if result.diagnostics.has_errors() {
        return Err(());
    }
    let Ok(bytes) = std::fs::read(file) else {
        eprintln!("error: cannot read {file}");
        return Err(());
    };
    // Content identity binds the bytes, not a lossy decode: non-UTF-8
    // sources must stay visibly distinct instead of being silently
    // approximated.
    Ok(emath_core::bootstrap_content_id(&bytes))
}

/// `doctor`: toolchain presence checks.
fn doctor_cmd(args: &[String]) -> u8 {
    if args.iter().any(|arg| arg == "--help" || arg == "-h") {
        println!(
            "doctor: checks rustc, cargo, rustfmt and clippy presence; exits 0 when all found"
        );
        return EXIT_OK;
    }
    let checks = [
        ("rustc", "rustc --version"),
        ("cargo", "cargo --version"),
        ("rustfmt", "rustfmt --version"),
        ("clippy", "cargo clippy --version"),
    ];
    let mut ok = true;
    for (name, probe) in checks {
        if let Some(version) = probe_program(probe) {
            println!("doctor: {name}: ok ({version})");
        } else {
            println!("doctor: {name}: MISSING");
            ok = false;
        }
    }
    if ok {
        EXIT_OK
    } else {
        EXIT_REFUSED
    }
}

fn probe_program(command: &str) -> Option<String> {
    let mut parts = command.split_whitespace();
    let program = parts.next()?;
    let output = Command::new(program).args(parts).output().ok()?;
    if output.status.success() {
        let text = String::from_utf8_lossy(&output.stdout).trim().to_string();
        Some(text.lines().next().unwrap_or(&text).to_string())
    } else {
        None
    }
}

/// `vendor --out <dir>`: offline dependency snapshot (zero third-party deps).
fn vendor_cmd(args: &[String]) -> u8 {
    let Some(out) = flag_value("--out", args).or_else(|| flag_value("-o", args)) else {
        return usage("vendor --out <dir>");
    };
    let lock = upstream_lock_path();
    let Ok(bytes) = std::fs::read(&lock) else {
        eprintln!(
            "error: E-TLT-007: upstream lock missing at {}",
            lock.display()
        );
        return EXIT_USAGE;
    };
    if bytes.is_empty() {
        eprintln!(
            "error: E-TLT-007: upstream lock is empty at {}",
            lock.display()
        );
        return EXIT_USAGE;
    }
    let Ok(text) = String::from_utf8(bytes) else {
        eprintln!(
            "error: E-TLT-007: upstream lock is not valid UTF-8 at {}",
            lock.display()
        );
        return EXIT_USAGE;
    };
    let entry_count = text.matches("      \"id\": \"").count();
    let mut object = JsonWriter::object();
    object.string("schema", "emath.vendor.v1");
    object.string("source", UPSTREAM_LOCK_REL);
    let source_id = content_id_of_str(&text).0;
    object.string("source_id", &source_id);
    object.int("upstream_pins", u64::try_from(entry_count).unwrap_or(0));
    object.int("third_party_deps", 0);
    object.bool("offline", true);
    let out_dir = PathBuf::from(out);
    if std::fs::create_dir_all(&out_dir).is_err() {
        eprintln!("error: cannot create {}", out_dir.display());
        return EXIT_USAGE;
    }
    let target = out_dir.join("vendor-manifest.json");
    let body = object.finish();
    if std::fs::write(&target, body.clone()).is_err() {
        eprintln!("error: cannot write {}", target.display());
        return EXIT_USAGE;
    }
    println!("vendor: wrote {body}");
    EXIT_OK
}

/// `provider list|inspect <id>|test <id>`.
fn provider_cmd(args: &[String]) -> u8 {
    let Some(sub) = args.first() else {
        return usage("provider list|inspect <id>|test <id>");
    };
    match sub.as_str() {
        "list" => {
            for (id, capability, status) in PROVIDERS {
                println!("provider {id}: {capability} [{status}]");
            }
            EXIT_OK
        }
        "inspect" => {
            let Some(id) = args.get(1) else {
                return usage("provider inspect <id>");
            };
            let Some((_, capability, status)) =
                PROVIDERS.iter().find(|(candidate, _, _)| candidate == id)
            else {
                eprintln!("error: E-TLT-016: unknown provider `{id}`");
                return EXIT_USAGE;
            };
            let mut object = JsonWriter::object();
            object.string("schema", "emath.provider-descriptor.v1");
            object.string("id", id);
            object.string("capability", capability);
            object.string("status", status);
            println!("{}", object.finish());
            EXIT_OK
        }
        "test" => {
            let Some(id) = args.get(1) else {
                return usage("provider test <id>");
            };
            let Some((_, _, status)) = PROVIDERS.iter().find(|(candidate, _, _)| candidate == id)
            else {
                eprintln!("error: E-TLT-016: unknown provider `{id}`");
                return EXIT_USAGE;
            };
            let _ = (status, id);
            // No in-CLI negative-control battery exists. Printing "suite:
            // ok" without running anything would be a fake success; refuse
            // with a typed code instead (same pattern as bench E-TLT-004).
            eprintln!("error: E-TLT-013: provider `{id}` has no in-CLI negative-control battery; run `cargo test` against tests/emath-adapter-rumoca in the workspace");
            EXIT_REFUSED
        }
        _ => usage("provider list|inspect <id>|test <id>"),
    }
}

/// `fork status|sync [--dry-run]`.
fn fork_cmd(args: &[String]) -> u8 {
    let Some(sub) = args.first() else {
        return usage("fork status|sync [--dry-run]");
    };
    let lock = upstream_lock_path();
    let Ok(bytes) = std::fs::read(&lock) else {
        eprintln!(
            "error: E-TLT-007: upstream lock missing at {}",
            lock.display()
        );
        return EXIT_USAGE;
    };
    if bytes.is_empty() {
        eprintln!(
            "error: E-TLT-007: upstream lock is empty at {}",
            lock.display()
        );
        return EXIT_USAGE;
    }
    let Ok(text) = String::from_utf8(bytes) else {
        eprintln!(
            "error: E-TLT-007: upstream lock is not valid UTF-8 at {}",
            lock.display()
        );
        return EXIT_USAGE;
    };
    match sub.as_str() {
        "status" => {
            for id in lock_ids(&text) {
                println!("fork {id}: pinned (lock {})", content_id_of_str(&text).0);
            }
            EXIT_OK
        }
        "sync" => {
            if args.iter().any(|arg| arg == "--dry-run") {
                println!(
                    "sync: dry-run: {} upstream pins unchanged (offline)",
                    lock_ids(&text).len()
                );
                EXIT_OK
            } else {
                eprintln!("error: E-TLT-006: network/source sync is disabled in Phase 1 (offline-first); use --dry-run");
                EXIT_REFUSED
            }
        }
        _ => usage("fork status|sync [--dry-run]"),
    }
}

/// Extracts quoted `"id": "..."` values from the lock document.
fn lock_ids(text: &str) -> Vec<String> {
    let mut ids = Vec::new();
    for line in text.lines() {
        let Some(rest) = line.trim().strip_prefix("\"id\": \"") else {
            continue;
        };
        if let Some(end) = rest.find('"') {
            ids.push(rest[..end].to_string());
        }
    }
    ids
}

/// `agent check|plan|build <file> ...`: structured envelope over the real
/// pipeline. The agent surface cannot bypass admission or artifact checks:
/// it renders the same session/build results as the interactive commands.
fn agent_cmd(args: &[String]) -> u8 {
    let Some(sub) = args.first() else {
        return usage("agent check|plan|build <file.emath> [--out <dir>]");
    };
    let positional = positional_args(&args[1..]);
    let file = positional.first();
    match sub.as_str() {
        "check" => {
            let Some(file) = file else {
                return usage("agent check <file.emath>");
            };
            let (diagnostics, package_id) = run_check(file);
            let admitted = !diagnostics.has_errors();
            let mut object = JsonWriter::object();
            object.string("schema", "emath.agent.v1");
            object.string("command", "check");
            object.bool("admitted", admitted);
            object.string("package", &package_id);
            object.int("diagnostics", diagnostics.len() as u64);
            let mut lines = String::new();
            for item in diagnostics.items() {
                lines.push_str(item.code);
                lines.push_str(": ");
                lines.push_str(&item.message);
                lines.push_str("; ");
            }
            object.string("diagnostics_text", &lines);
            println!("{}", object.finish());
            if admitted {
                EXIT_OK
            } else {
                EXIT_REFUSED
            }
        }
        "plan" => {
            let Some(file) = file else {
                return usage("agent plan <file.emath>");
            };
            let mut session = CompilerSession::new(emath_core::limits::Limits::default());
            let Ok(package) = session.load_package(file) else {
                eprintln!("error: cannot read {file}");
                return EXIT_USAGE;
            };
            let result = session.plan(package.file);
            let mut object = JsonWriter::object();
            object.string("schema", "emath.agent.v1");
            object.string("command", "plan");
            object.bool("admitted", !result.diagnostics.has_errors());
            object.int("goals", result.package.goals.len() as u64);
            object.int("plans", result.plans.len() as u64);
            let mut goals = String::new();
            for goal in &result.package.goals {
                goals.push_str(goal.kind.as_str());
                goals.push(' ');
                goals.push_str(goal.target.as_str());
                goals.push(' ');
            }
            object.string("goals", &goals);
            println!("{}", object.finish());
            if result.diagnostics.has_errors() {
                EXIT_REFUSED
            } else {
                EXIT_OK
            }
        }
        "build" => {
            let Some(file) = file else {
                return usage("agent build <file.emath> --out <dir>");
            };
            let Some(out) = flag_value("--out", args).or_else(|| flag_value("-o", args)) else {
                return usage("agent build <file.emath> --out <dir>");
            };
            match build_file(
                file,
                PathBuf::from(out),
                BuildOptions {
                    // The agent surface cannot bypass artifact checks: a
                    // generated crate with no #[test] tests is refused
                    // (E-TLT-012) exactly like `emath test`.
                    verify_generated_crate: true,
                },
            ) {
                Ok(report) => {
                    let mut object = JsonWriter::object();
                    object.string("schema", "emath.agent.v1");
                    object.string("command", "build");
                    object.string("artifact_id", &report.artifact_id.0);
                    object.string("package_id", &report.package_id.0);
                    object.string("crate", &report.crate_name);
                    object.string("artifact_dir", &report.artifact_dir.display().to_string());
                    println!("{}", object.finish());
                    EXIT_OK
                }
                Err(error) => {
                    eprintln!("error: {error}");
                    classify_build_error(&error)
                }
            }
        }
        _ => usage("agent check|plan|build <file.emath> [--out <dir>]"),
    }
}

/// Mirrors `crate::run_check` for the agent envelope (same admission path).
fn run_check(path: &str) -> (emath_core::Diagnostics, String) {
    let mut session = CompilerSession::new(emath_core::limits::Limits::default());
    let Ok(package) = session.load_package(path) else {
        return (emath_core::Diagnostics::new(), String::new());
    };
    let result = session.check(package.file);
    (result.diagnostics, result.package.content_id().0)
}

/// Maps a build error to the conventional exit class.
fn classify_build_error(error: &dyn std::fmt::Display) -> u8 {
    let text = error.to_string();
    if text.contains("admission refused") {
        EXIT_REFUSED
    } else {
        EXIT_USAGE
    }
}

fn positional_args(args: &[String]) -> Vec<String> {
    args.iter()
        .filter(|arg| !arg.starts_with('-'))
        .cloned()
        .collect()
}

fn first_positional(args: &[String]) -> Option<String> {
    positional_args(args).first().cloned()
}

fn flag_value(flag: &str, args: &[String]) -> Option<String> {
    args.iter()
        .position(|arg| arg == flag)
        .and_then(|index| args.get(index + 1))
        .cloned()
}

fn usage(message: &str) -> u8 {
    eprintln!("usage: emath {message}");
    eprintln!("run `emath help` for the full command list");
    EXIT_USAGE
}
