//! `emath migrate` CLI.
mod common;
use common::cli;
use emath_test_harness::Probe;
fn scratch(name: &str) -> std::path::PathBuf { let d = std::env::temp_dir().join(format!("emath_migrate_{name}")); let _ = std::fs::remove_dir_all(&d); std::fs::create_dir_all(&d).expect("dir"); d }
const NON_CANONICAL: &str = "emath function plain:\n    inputs:\n        x: Float64\n\n    outputs:\n        y: Float64\n\n    definitions:\n        y=x*2.0\n";
const REFUSING: &str = "emath function broken:\n    inputs:\n        x: Float64\n\n    outputs:\n        y: Float64\n\n    definitions:\n        y = undefined_name\n";
#[test]
fn probe() {
    let mut p = Probe::new("migrate checks without writing, fixes idempotently, receipts canonically, refuses safely");
    p.case("check", |p| { let d = scratch("check"); let f = d.join("plain.emath"); std::fs::write(&f, NON_CANONICAL).expect("w"); let fp = f.to_str().expect("utf8").to_string(); let (out, code) = cli(&["migrate", &fp, "--check"]); p.eq("exit", code, 1); p.contains("rule", &out, "E-MIG-RULE-001"); p.eq("untouched", std::fs::read_to_string(&f).expect("r"), NON_CANONICAL.to_string()); });
    p.case("fix", |p| { let d = scratch("fix_ok"); let f = d.join("plain.emath"); std::fs::write(&f, NON_CANONICAL).expect("w"); let fp = f.to_str().expect("utf8").to_string(); let (out, code) = cli(&["migrate", &fp, "--fix"]); p.eq("exit", code, 0); let canon = std::fs::read_to_string(&f).expect("r"); p.ne("rewritten", canon.clone(), NON_CANONICAL.to_string()); let (out2, code2) = cli(&["migrate", &fp, "--check"]); p.eq("idempotent", code2, 0); p.eq("stable", std::fs::read_to_string(&f).expect("r"), canon); let _ = out; let _ = out2; });
    p.case("receipt", |p| { let d = scratch("receipt"); let f = d.join("plain.emath"); std::fs::write(&f, NON_CANONICAL).expect("w"); let (fp, r1, r2) = (f.to_str().expect("utf8").to_string(), d.join("mig.json"), d.join("mig2.json")); let (rp1, rp2) = (r1.to_str().expect("utf8").to_string(), r2.to_str().expect("utf8").to_string()); let (out, code) = cli(&["migrate", &fp, "--fix", "--receipt", &rp1]); p.eq("exit", code, 0); let rec = std::fs::read_to_string(&r1).expect("receipt"); for needle in ["{\"schema\":\"emath.migration-receipt v1\"", "\"kind\":\"respell\"", "\"identity_delta\":\"none\"", "\"identity_verified\":true", "\"verdict\":\"complete\"", "E-MIG-RULE-001"] { p.contains(needle, &rec, needle); } std::fs::write(&f, NON_CANONICAL).expect("restore"); let _ = cli(&["migrate", &fp, "--fix", "--receipt", &rp2]); p.eq("replay", std::fs::read_to_string(&r2).expect("r2"), rec); let _ = out; });
    p.case("no-fix", |p| { let d = scratch("nofix"); let f = d.join("plain.emath"); std::fs::write(&f, NON_CANONICAL).expect("w"); let (out, code) = cli(&["migrate", f.to_str().expect("utf8")]); p.eq("exit", code, 1); p.eq("untouched", std::fs::read_to_string(&f).expect("r"), NON_CANONICAL.to_string()); let _ = out; });
    p.case("refusing", |p| { let d = scratch("refusing"); let f = d.join("broken.emath"); std::fs::write(&f, REFUSING).expect("w"); let r = d.join("mig.json"); let (out, code) = cli(&["migrate", f.to_str().expect("utf8"), "--receipt", r.to_str().expect("utf8")]); p.eq("exit", code, 1); p.contains("code", &out, "E-MIG-SOURCE-REFUSES"); let rec = std::fs::read_to_string(&r).expect("receipt"); p.contains("receipt-code", &rec, "E-MIG-SOURCE-REFUSES"); p.contains("verdict", &rec, "\"verdict\":\"partial-refused\""); p.eq("untouched", std::fs::read_to_string(&f).expect("r"), REFUSING.to_string()); });
    p.case("registry", |p| { let (out, code) = cli(&["migrate", "--list-rules"]); p.eq("exit", code, 0); p.contains("rule", &out, "E-MIG-RULE-001"); p.contains("name", &out, "canonical-format"); });
    p.finish();
}
