//! Deterministic interpretation portfolio tests.
use emath_cli::portfolio::{Authority, InterpretationCandidate, InterpretationPortfolio, ScoreVector, translated_candidate};
use emath_term::{Signature, SymbolId};
use emath_world_ir::translation::{CarrierMap, FastPathGuard, PreservationObligation, PreservationRelation, StrictFastPortfolio, WorldMorphism};
use emath_world_ir::{CarrierDef, Fixity, MeaningOrigin, OperatorDef, OperatorSemantics, SymbolDef, WORLD_IR_VERSION, WorldId, WorldIr};
use emath_test_harness::{Case, Probe, check_all, expect_ok};
fn candidate(id: u64, name: &str, authority: Authority, utility: f64, cost: f64) -> InterpretationCandidate { InterpretationCandidate { world_id: WorldId(id), name: name.into(), answer: String::new(), authority, score: ScoreVector { cost, complexity: 1.0, evidence: 0.0, utility }, provenance: String::new() } }
fn small_world(name: &str, law: &str) -> WorldIr { let mut sig = Signature::default(); let sym = SymbolId("op".into()); sig.insert(sym.clone(), 1).unwrap(); WorldIr { version: WORLD_IR_VERSION, name: name.into(), signature: sig, carriers: vec![CarrierDef { name: "C".into(), type_expression: "carrier".into() }], symbols: vec![SymbolDef { id: sym.clone(), display: name.into(), fixity: Fixity::Prefix, precedence: None, type_scheme: "C → C".into() }], operators: vec![OperatorDef { symbol: sym, semantics: OperatorSemantics::StructuralConstructor, origin: MeaningOrigin::Declared }], constructors: vec![], laws: vec![law.into()], effects: vec![], holes: vec![], capabilities: vec![] } }
fn morphism(source: WorldId, target: WorldId, relation: PreservationRelation) -> WorldMorphism { WorldMorphism::new(source, target, vec![CarrierMap { source_carrier: "C".into(), target_carrier: "C".into(), mapping: "id".into() }], vec![PreservationObligation { symbol: SymbolId("op".into()), relation, obligation: "map(op(x)) == op(map(x))".into() }], vec![]) }
#[test]
fn probe() {
    let mut p = Probe::new("portfolio orders by authority then utility, translates cap authority");
    expect_ok(check_all(&[Case::new("policy", vec![(3, "cheap-structural", Authority::Structural, 5.0, 1.0), (1, "tested", Authority::Tested, 1.0, 9.0), (2, "useful-structural", Authority::Structural, 9.0, 5.0)], vec!["tested".to_string(), "useful-structural".to_string(), "cheap-structural".to_string()]), Case::new("tie", vec![(9, "b", Authority::Structural, 1.0, 1.0), (4, "a", Authority::Structural, 1.0, 1.0)], vec!["a".to_string(), "b".to_string()])], |rows| InterpretationPortfolio::new(rows.iter().map(|(id, n, a, u, c)| candidate(*id, n, *a, *u, *c)).collect::<Vec<_>>()).candidates().iter().map(|c| c.name.clone()).collect::<Vec<_>>()));
    p.case("exit-gate", |p| { let (a, b) = (small_world("A", "law-a"), small_world("B", "law-b")); let m = morphism(a.identity(), b.identity(), PreservationRelation::Exact); let fast = StrictFastPortfolio::new(a.clone(), b.clone(), m.clone(), FastPathGuard { domain: "input < 8".into(), required_evidence: vec![] }).expect("invariants"); let (sel, reason) = fast.select_world(&[SymbolId("op".into())], false, true); p.eq("deopt", sel, a.identity()); p.demand("reason", reason.is_some(), "failed guard must deopt"); let base = InterpretationCandidate { world_id: a.identity(), name: "strict".into(), answer: "7".into(), authority: Authority::Tested, score: ScoreVector { cost: 1.0, complexity: 1.0, evidence: 1.0, utility: 1.0 }, provenance: "base".into() }; let t = translated_candidate(&m, &base, "7".into()); p.eq("world", t.world_id, b.identity()); p.contains("morphism", &t.provenance, &format!("morphism:{:x}", m.identity())); let pf = InterpretationPortfolio::new(vec![t, base]); p.eq("len", pf.candidates().len(), 2); let mut ids: Vec<WorldId> = pf.candidates().iter().map(|c| c.world_id).collect(); let mut exp = vec![a.identity(), b.identity()]; exp.sort(); ids.sort(); p.eq("ids", ids, exp); });
    p.case("cap", |p| { let base = candidate(1, "tested", Authority::Tested, 1.0, 1.0); p.eq("approx", translated_candidate(&morphism(WorldId(1), WorldId(2), PreservationRelation::Approximation), &base, "approx".into()).authority, Authority::Structural); p.eq("exact", translated_candidate(&morphism(WorldId(1), WorldId(2), PreservationRelation::Exact), &base, "exact".into()).authority, Authority::Tested); });
    p.finish();
}
