#![forbid(unsafe_code)]

//! Deterministic parametric Rust world artifact generation (Semantic Genesis G3).
//!
//! Emits a self-contained, zero-dependency generated crate evaluating a fixed
//! first-order term under free-symbolic, Boolean, and modular-17 worlds, plus
//! a negative-control world whose `⋈`/`⊛` semantics are swapped.

use emath_term::{Signature, Term};
use std::collections::BTreeMap;
use std::path::Path;

/// A world whose implementation is generated.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WorldSpec {
    /// Stable label: `free_symbolic`, `boolean_algebra`, or `modular_numeric`.
    pub label: String,
}

/// Deterministic generated package.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedPackage {
    /// Crate name.
    pub crate_name: String,
    /// Relative path → file content.
    pub files: BTreeMap<String, String>,
}

impl GeneratedPackage {
    /// Writes every file under `dir`, replacing existing files.
    pub fn write_to(&self, dir: &Path) -> std::io::Result<()> {
        std::fs::create_dir_all(dir)?;
        for (relative, body) in &self.files {
            let target = dir.join(relative);
            if let Some(parent) = target.parent() {
                std::fs::create_dir_all(parent)?;
            }
            std::fs::write(target, body)?;
        }
        Ok(())
    }
}

/// Emits the parametric crate for `term` under `signature`.
#[must_use]
pub fn generate(term: &Term, signature: &Signature, worlds: &[WorldSpec]) -> GeneratedPackage {
    let labels = worlds
        .iter()
        .map(|spec| spec.label.clone())
        .collect::<Vec<_>>();
    let mut files = BTreeMap::new();
    files.insert("Cargo.toml".into(), render_manifest());
    files.insert("src/lib.rs".into(), render_lib(term, signature, &labels));
    files.insert("src/main.rs".into(), render_main(&labels));
    GeneratedPackage {
        crate_name: "semantic-genesis-worlds".into(),
        files,
    }
}

fn render_manifest() -> String {
    r#"# Generated by eMath Semantic Genesis (deterministic; do not edit).
[package]
name = "semantic-genesis-worlds"
version = "0.1.0"
edition = "2021"
description = "Generated parametric worlds for the reference alien signature."
license = "MIT OR Apache-2.0"

[lib]
path = "src/lib.rs"

[[bin]]
name = "semantic-genesis-worlds"
path = "src/main.rs"

[dependencies]
"#
    .to_string()
}

const LIB_TEMPLATE: &str = r#"#![forbid(unsafe_code)]

//! Generated by eMath Semantic Genesis (deterministic; do not edit).
//!
//! Source signature: @@ARITIES@@.

use std::collections::BTreeMap;
use std::fmt;
use std::fmt::Write as _;

/// Canonical first-order term (self-contained model).
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Term {
    /// Free variable.
    Variable(String),
    /// Nullary symbol.
    Constant(String),
    /// Operator applied to ordered arguments.
    Apply {
        /// Operator name.
        operator: String,
        /// Argument terms.
        arguments: Vec<Term>,
    },
}

impl Term {
    /// Renders the deterministic structural canonical form.
    #[must_use]
    pub fn canonical(&self) -> String {
        let mut output = String::new();
        self.write_canonical(&mut output)
            .expect("writing into String cannot fail");
        output
    }

    fn write_canonical(&self, output: &mut String) -> fmt::Result {
        match self {
            Self::Variable(name) => write!(output, "var({})", escape(name)),
            Self::Constant(name) => write!(output, "const({})", escape(name)),
            Self::Apply {
                operator,
                arguments,
            } => {
                write!(output, "apply({}", escape(operator))?;
                for argument in arguments {
                    output.push(',');
                    argument.write_canonical(output)?;
                }
                output.push(')');
                Ok(())
            }
        }
    }

    /// Parses the canonical form produced by [`Term::canonical`].
    pub fn parse_canonical(text: &str) -> Result<Self, String> {
        let mut parser = CanonicalParser {
            bytes: text.as_bytes(),
            pos: 0,
        };
        let term = parser.parse_term()?;
        if parser.pos != parser.bytes.len() {
            return Err(format!("trailing content at {}", parser.pos));
        }
        Ok(term)
    }
}

fn escape(text: &str) -> String {
    let mut result = String::with_capacity(text.len());
    for ch in text.chars() {
        match ch {
            '\\' => result.push_str("\\\\"),
            '(' => result.push_str("\\("),
            ')' => result.push_str("\\)"),
            ',' => result.push_str("\\,"),
            _ => result.push(ch),
        }
    }
    result
}

struct CanonicalParser<'a> {
    bytes: &'a [u8],
    pos: usize,
}

impl CanonicalParser<'_> {
    fn peek(&self) -> Option<u8> {
        self.bytes.get(self.pos).copied()
    }

    fn eat(&mut self, expected: &str) -> bool {
        if self.bytes[self.pos..].starts_with(expected.as_bytes()) {
            self.pos += expected.len();
            true
        } else {
            false
        }
    }

    fn malformed(&self) -> String {
        format!("malformed canonical at {}", self.pos)
    }

    fn parse_term(&mut self) -> Result<Term, String> {
        if self.eat("var") {
            if !self.eat("(") {
                return Err(self.malformed());
            }
            let name = self.parse_name(false)?;
            if !self.eat(")") {
                return Err(self.malformed());
            }
            return Ok(Term::Variable(name));
        }
        if self.eat("const") {
            if !self.eat("(") {
                return Err(self.malformed());
            }
            let name = self.parse_name(false)?;
            if !self.eat(")") {
                return Err(self.malformed());
            }
            return Ok(Term::Constant(name));
        }
        if !self.eat("apply") {
            return Err(self.malformed());
        }
        if !self.eat("(") {
            return Err(self.malformed());
        }
        let operator = self.parse_name(true)?;
        let mut arguments = Vec::new();
        loop {
            if self.eat(")") {
                return Ok(Term::Apply {
                    operator,
                    arguments,
                });
            }
            if !self.eat(",") {
                return Err(self.malformed());
            }
            arguments.push(self.parse_term()?);
        }
    }

    fn parse_name(&mut self, stop_at_comma: bool) -> Result<String, String> {
        let mut name = String::new();
        while let Some(byte) = self.peek() {
            if byte == b'\\' {
                self.pos += 1;
                let Some(escaped) = self.peek() else {
                    return Err(self.malformed());
                };
                name.push(char::from(escaped));
                self.pos += 1;
                continue;
            }
            if byte == b')' || (stop_at_comma && byte == b',') {
                return Ok(name);
            }
            let rest =
                std::str::from_utf8(&self.bytes[self.pos..]).map_err(|_| self.malformed())?;
            let Some(ch) = rest.chars().next() else {
                return Err(self.malformed());
            };
            name.push(ch);
            self.pos += ch.len_utf8();
        }
        Err(self.malformed())
    }
}

/// Generic first-order world implementation.
pub trait World {
    /// Runtime value.
    type Value: Clone + fmt::Display;
    /// Evaluation error.
    type Error: fmt::Display + fmt::Debug;

    /// Resolves a nullary symbol.
    fn constant(&self, symbol: &str) -> Result<Self::Value, Self::Error>;

    /// Applies an operator to evaluated arguments.
    fn apply(
        &self,
        operator: &str,
        arguments: Vec<Self::Value>,
    ) -> Result<Self::Value, Self::Error>;
}

/// Evaluation error shared by the generated worlds.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum EvalError {
    /// Missing free-variable valuation.
    MissingVariable(String),
    /// Unknown symbol.
    UnknownSymbol(String),
    /// Incorrect runtime arity.
    Arity {
        /// Symbol.
        symbol: String,
        /// Expected arity.
        expected: usize,
        /// Actual arity.
        actual: usize,
    },
}

impl fmt::Display for EvalError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{self:?}")
    }
}

impl std::error::Error for EvalError {}

/// Environment for free variables.
pub type Environment<V> = BTreeMap<String, V>;

/// Evaluates a term in any world implementing its symbols.
pub fn evaluate<W: World>(
    term: &Term,
    world: &W,
    environment: &Environment<W::Value>,
) -> Result<W::Value, W::Error>
where
    W::Error: From<EvalError>,
{
    match term {
        Term::Variable(name) => environment
            .get(name)
            .cloned()
            .ok_or_else(|| EvalError::MissingVariable(name.clone()).into()),
        Term::Constant(symbol) => world.constant(symbol),
        Term::Apply {
            operator,
            arguments,
        } => {
            let values = arguments
                .iter()
                .map(|argument| evaluate(argument, world, environment))
                .collect::<Result<Vec<_>, _>>()?;
            world.apply(operator, values)
        }
    }
}

/// The reference term this crate evaluates.
///
/// Canonical: @@REFERENCE_CANONICAL@@
#[must_use]
pub fn reference_term() -> Term {
    Term::parse_canonical(@@REFERENCE_CANONICAL@@)
        .expect("reference canonical parses")
}

/// Free symbolic world: values remain canonical term strings.
#[derive(Debug, Default, Clone, Copy)]
pub struct FreeSymbolicWorld;

impl World for FreeSymbolicWorld {
    type Value = String;
    type Error = EvalError;

    fn constant(&self, symbol: &str) -> Result<Self::Value, Self::Error> {
        Ok(format!("const({})", escape(symbol)))
    }

    fn apply(
        &self,
        operator: &str,
        arguments: Vec<Self::Value>,
    ) -> Result<Self::Value, Self::Error> {
        let mut result = String::from("apply(");
        result.push_str(&escape(operator));
        for argument in arguments {
            result.push(',');
            result.push_str(&argument);
        }
        result.push(')');
        Ok(result)
    }
}

/// Boolean interpretation of the reference signature.
#[derive(Debug, Default, Clone, Copy)]
pub struct BooleanWorld;

impl World for BooleanWorld {
    type Value = bool;
    type Error = EvalError;

    fn constant(&self, symbol: &str) -> Result<Self::Value, Self::Error> {
        match symbol {
            "ζ" => Ok(true),
            _ => Err(EvalError::UnknownSymbol(symbol.into())),
        }
    }

    fn apply(
        &self,
        operator: &str,
        arguments: Vec<Self::Value>,
    ) -> Result<Self::Value, Self::Error> {
        match (operator, arguments.as_slice()) {
            ("⋈", [left, right]) => Ok(*left ^ *right),
            ("⧖", [value]) => Ok(!*value),
            ("⊛", [left, right]) => Ok(*left && *right),
            ("⋈" | "⊛", values) => Err(EvalError::Arity {
                symbol: operator.into(),
                expected: 2,
                actual: values.len(),
            }),
            ("⧖", values) => Err(EvalError::Arity {
                symbol: operator.into(),
                expected: 1,
                actual: values.len(),
            }),
            _ => Err(EvalError::UnknownSymbol(operator.into())),
        }
    }
}

/// Modular-17 interpretation of the reference signature.
#[derive(Debug, Default, Clone, Copy)]
pub struct ModularWorld;

impl World for ModularWorld {
    type Value = i64;
    type Error = EvalError;

    fn constant(&self, symbol: &str) -> Result<Self::Value, Self::Error> {
        match symbol {
            "ζ" => Ok(3),
            _ => Err(EvalError::UnknownSymbol(symbol.into())),
        }
    }

    fn apply(
        &self,
        operator: &str,
        arguments: Vec<Self::Value>,
    ) -> Result<Self::Value, Self::Error> {
        let modulo = |value: i64| value.rem_euclid(17);
        match (operator, arguments.as_slice()) {
            ("⋈", [left, right]) => Ok(modulo(*left + *right)),
            ("⧖", [value]) => Ok(modulo(*value * *value)),
            ("⊛", [left, right]) => Ok(modulo(*left * *right)),
            ("⋈" | "⊛", values) => Err(EvalError::Arity {
                symbol: operator.into(),
                expected: 2,
                actual: values.len(),
            }),
            ("⧖", values) => Err(EvalError::Arity {
                symbol: operator.into(),
                expected: 1,
                actual: values.len(),
            }),
            _ => Err(EvalError::UnknownSymbol(operator.into())),
        }
    }
}

/// Negative control: modular semantics with `⋈` and `⊛` swapped.
/// Differential evaluation must reject this world.
#[derive(Debug, Default, Clone, Copy)]
pub struct SwappedModularWorld;

impl World for SwappedModularWorld {
    type Value = i64;
    type Error = EvalError;

    fn constant(&self, symbol: &str) -> Result<Self::Value, Self::Error> {
        match symbol {
            "ζ" => Ok(3),
            _ => Err(EvalError::UnknownSymbol(symbol.into())),
        }
    }

    fn apply(
        &self,
        operator: &str,
        arguments: Vec<Self::Value>,
    ) -> Result<Self::Value, Self::Error> {
        let modulo = |value: i64| value.rem_euclid(17);
        match (operator, arguments.as_slice()) {
            ("⋈", [left, right]) => Ok(modulo(*left * *right)),
            ("⊛", [left, right]) => Ok(modulo(*left + *right)),
            ("⧖", [value]) => Ok(modulo(*value * *value)),
            ("⋈" | "⊛", values) => Err(EvalError::Arity {
                symbol: operator.into(),
                expected: 2,
                actual: values.len(),
            }),
            ("⧖", values) => Err(EvalError::Arity {
                symbol: operator.into(),
                expected: 1,
                actual: values.len(),
            }),
            _ => Err(EvalError::UnknownSymbol(operator.into())),
        }
    }
}

/// Free-symbolic fixture: variables remain canonical strings.
#[must_use]
pub fn fixture_free() -> Environment<String> {
    let mut environment = Environment::new();
    environment.insert("a".into(), "var(a)".into());
    environment.insert("b".into(), "var(b)".into());
    environment
}

/// Boolean fixture: a=true, b=false.
#[must_use]
pub fn fixture_boolean() -> Environment<bool> {
    let mut environment = Environment::new();
    environment.insert("a".into(), true);
    environment.insert("b".into(), false);
    environment
}

/// Modular-17 fixture: a=4, b=7.
#[must_use]
pub fn fixture_modular() -> Environment<i64> {
    let mut environment = Environment::new();
    environment.insert("a".into(), 4);
    environment.insert("b".into(), 7);
    environment
}

#[cfg(test)]
mod tests {
    use super::{
        evaluate, fixture_boolean, fixture_free, fixture_modular, reference_term, BooleanWorld,
        FreeSymbolicWorld, ModularWorld, SwappedModularWorld,
    };

    #[test]
    fn free_symbolic_world_preserves_structure() {
        let term = reference_term();
        let result = evaluate(&term, &FreeSymbolicWorld, &fixture_free()).unwrap();
        assert_eq!(result, term.canonical());
    }

    #[test]
    fn boolean_world_matches_fixture() {
        let term = reference_term();
        let result = evaluate(&term, &BooleanWorld, &fixture_boolean()).unwrap();
        assert!(!result);
    }

    #[test]
    fn modular_world_matches_fixture() {
        let term = reference_term();
        let result = evaluate(&term, &ModularWorld, &fixture_modular()).unwrap();
        assert_eq!(result, 6);
    }

    #[test]
    fn wrong_world_is_rejected() {
        let term = reference_term();
        let result = evaluate(&term, &SwappedModularWorld, &fixture_modular()).unwrap();
        assert_ne!(result, 6);
    }
}
"#;

fn render_lib(term: &Term, signature: &Signature, labels: &[String]) -> String {
    let _ = labels;
    LIB_TEMPLATE
        .replace(
            "@@ARITIES@@",
            &signature
                .iter()
                .map(|(symbol, arity)| format!("{}:{}", symbol.0, arity))
                .collect::<Vec<_>>()
                .join(", "),
        )
        .replace("@@REFERENCE_CANONICAL@@", &rust_string(&term.canonical()))
}

/// Rust string literal escaping (default settings; Unicode glyphs inline).
fn rust_string(text: &str) -> String {
    let mut out = String::with_capacity(text.len() + 2);
    out.push('"');
    for ch in text.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            '\r' => out.push_str("\\r"),
            _ => out.push(ch),
        }
    }
    out.push('"');
    out
}

const MAIN_TEMPLATE: &str = r#"#![forbid(unsafe_code)]

// Generated by eMath Semantic Genesis (deterministic; do not edit).
@@USES@@
fn main() {
    let term = reference_term();
    let free = evaluate(&term, &FreeSymbolicWorld, &fixture_free()).expect("free evaluates");
    println!("free: {free}");
@@BOOLEAN_BODY@@
@@MODULAR_BODY@@
}
"#;

fn render_main(labels: &[String]) -> String {
    let mut uses = String::from(
        "use semantic_genesis_worlds::{evaluate, fixture_free, reference_term, FreeSymbolicWorld};\n",
    );
    if labels.iter().any(|label| label == "boolean_algebra") {
        uses.push_str("use semantic_genesis_worlds::{fixture_boolean, BooleanWorld};\n");
    }
    if labels.iter().any(|label| label == "modular_numeric") {
        uses.push_str(
            "use semantic_genesis_worlds::{fixture_modular, ModularWorld, SwappedModularWorld};\n",
        );
    }
    let mut boolean_body = String::new();
    if labels.iter().any(|label| label == "boolean_algebra") {
        boolean_body
            .push_str("    let boolean = evaluate(&term, &BooleanWorld, &fixture_boolean()).expect(\"boolean evaluates\");\n    println!(\"boolean: {boolean}\");\n");
    }
    let mut modular_body = String::new();
    if labels.iter().any(|label| label == "modular_numeric") {
        modular_body.push_str(
            "    let modular = evaluate(&term, &ModularWorld, &fixture_modular()).expect(\"modular evaluates\");\n    println!(\"modular-17: {modular}\");\n    let swapped =\n        evaluate(&term, &SwappedModularWorld, &fixture_modular()).expect(\"swapped evaluates\");\n    println!(\"swapped-modular-17: {swapped}\");\n",
        );
    }
    MAIN_TEMPLATE
        .replace("@@USES@@", uses.trim_end())
        .replace("@@BOOLEAN_BODY@@", boolean_body.trim_end())
        .replace("@@MODULAR_BODY@@", modular_body.trim_end())
}

#[cfg(test)]
mod tests {
    use super::*;
    use emath_term::{SymbolId, VariableId};

    fn reference_term() -> Term {
        Term::Apply {
            operator: SymbolId("⊛".into()),
            arguments: vec![
                Term::Apply {
                    operator: SymbolId("⧖".into()),
                    arguments: vec![Term::Apply {
                        operator: SymbolId("⋈".into()),
                        arguments: vec![
                            Term::Variable(VariableId("a".into())),
                            Term::Variable(VariableId("b".into())),
                        ],
                    }],
                },
                Term::Constant(SymbolId("ζ".into())),
            ],
        }
    }

    fn reference_signature() -> Signature {
        let mut signature = Signature::default();
        signature.insert(SymbolId("⧖".into()), 1).unwrap();
        signature.insert(SymbolId("⋈".into()), 2).unwrap();
        signature.insert(SymbolId("⊛".into()), 2).unwrap();
        signature.insert(SymbolId("ζ".into()), 0).unwrap();
        signature
    }

    fn all_worlds() -> Vec<WorldSpec> {
        ["free_symbolic", "boolean_algebra", "modular_numeric"]
            .iter()
            .map(|label| WorldSpec {
                label: (*label).into(),
            })
            .collect()
    }

    #[test]
    fn generation_is_deterministic() {
        let signature = reference_signature();
        let term = reference_term();
        let first = generate(&term, &signature, &all_worlds());
        let second = generate(&term, &signature, &all_worlds());
        assert_eq!(first.files, second.files);
        assert_eq!(first.files.len(), 3);
        for (path, body) in &first.files {
            assert!(!body.is_empty(), "{path} rendered empty");
        }
    }

    #[test]
    fn generated_crate_contains_all_worlds_and_negative_control() {
        let signature = reference_signature();
        let term = reference_term();
        let generated = generate(&term, &signature, &all_worlds());
        let lib = &generated.files["src/lib.rs"];
        for marker in [
            "pub struct FreeSymbolicWorld",
            "pub struct BooleanWorld",
            "pub struct ModularWorld",
            "pub struct SwappedModularWorld",
            "mod tests",
            "assert_ne!(result, 6)",
        ] {
            assert!(lib.contains(marker), "missing {marker}");
        }
        let main = &generated.files["src/main.rs"];
        for line in [
            "free: {free}",
            "boolean: {boolean}",
            "modular-17: {modular}",
            "swapped-modular-17: {swapped}",
        ] {
            assert!(main.contains(line), "missing print {line}");
        }
    }

    #[test]
    fn write_to_materializes_files() {
        let signature = reference_signature();
        let term = reference_term();
        let generated = generate(&term, &signature, &all_worlds());
        let dir = std::env::temp_dir().join(format!("emath-codegen-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        generated.write_to(&dir).unwrap();
        assert!(dir.join("Cargo.toml").is_file());
        assert!(dir.join("src/lib.rs").is_file());
        assert!(dir.join("src/main.rs").is_file());
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn emitted_lib_includes_reference_term_canonical() {
        let signature = reference_signature();
        let term = reference_term();
        let generated = generate(&term, &signature, &all_worlds());
        let lib = &generated.files["src/lib.rs"];
        assert!(lib.contains(&term.canonical()));
    }
}
