[package]
name = "emath-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "emath"
path = "src/main.rs"

[dependencies]
emath-artifact = { workspace = true }
emath-build = { workspace = true }
emath-core = { workspace = true }
emath-genesis = { workspace = true }
emath-goal = { workspace = true }
emath-ir = { workspace = true }
emath-plan = { workspace = true }
emath-portfolio = { workspace = true }
emath-rust-backend = { workspace = true }
emath-sema = { workspace = true }
emath-source = { workspace = true }
emath-syntax = { workspace = true }
emath-term = { workspace = true }
emath-world-codegen-rust = { workspace = true }
emath-world-ir = { workspace = true }

[lints]
workspace = true
