[package]
name = "emath-wasm-tests"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
emath-wasm = { workspace = true }
emath-core = { workspace = true }
emath-exec-ir = { workspace = true }
emath-artifact = { workspace = true }
emath-test-harness = { workspace = true }

[lints.rust]
unsafe_code = "deny"

[lints.clippy]
all = { level = "warn", priority = -1 }
