[package]
name = "emath-rust-backend-tests"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
emath-rust-backend = { path = "../../crates/emath-rust-backend" }
emath-rust-ir = { path = "../../crates/emath-rust-ir" }
emath-core = { path = "../../crates/emath-core" }
emath-ir = { path = "../../crates/emath-ir" }
