#!/usr/bin/env python3
r"""Dump the emitted E-code inventory to a Markdown completeness annex.

The annex lists every stable diagnostic code emitted by the production
crates (`crates/**/*.rs`, excluding build output), with its emitting
files and a message context snippet. The workspace test
`crates/emath-hir/tests/registry_complete.rs` independently re-derives
the emitted set (same extraction rule: `\bE-[A-Z]+-\d{3}\b`) and asserts
it is a subset of the codes named in `implementation/ERROR_CODES.md`,
including this annex. Doc-comment family patterns such as `E-SYN-2xx`
are not emissions and are intentionally not matched.

Usage: python3 scripts/dump_error_codes.py
"""

import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
CRATES = os.path.join(ROOT, "crates")
DOC = os.path.join(ROOT, "implementation", "ERROR_CODES.md")

CODE_RE = re.compile(r"\bE-[A-Z]+-\d{3}\b")
STRING_RE = re.compile(r'"([^"\\]*(?:\\.[^"\\]*)*)"')


def iter_rust_files():
    for crate in sorted(os.listdir(CRATES)):
        crate_root = os.path.join(CRATES, crate)
        if not os.path.isdir(crate_root):
            continue
        for dirpath, dirnames, filenames in os.walk(crate_root):
            dirnames[:] = [d for d in dirnames if d not in ("target", ".git")]
            for fn in sorted(filenames):
                if fn.endswith(".rs"):
                    yield os.path.join(dirpath, fn)


def context_snippet(lines, line_idx, code):
    """Return the message text near the emission, if any."""
    search_range = lines[line_idx : min(line_idx + 4, len(lines))]
    for candidate in search_range:
        fmt = re.search(r'format!\s*\(\s*"([^"]*)"', candidate)
        if fmt:
            return fmt.group(1)[:110]
    for candidate in search_range:
        m = STRING_RE.search(candidate)
        if m and m.group(1).strip():
            return m.group(1)[:110]
    return ""


def main():
    check_mode = "--check" in sys.argv
    emissions = {}  # code -> {files: set, snippets: list}
    rust_files = list(iter_rust_files())
    for path in rust_files:
        rel = os.path.relpath(path, ROOT).replace(os.path.sep, "/")
        with open(path, encoding="utf-8") as fh:
            lines = fh.read().splitlines()
        for idx, line in enumerate(lines):
            for m in CODE_RE.finditer(line):
                code = m.group(0)
                entry = emissions.setdefault(code, {"files": set(), "snippets": []})
                entry["files"].add(rel)
                snippet = context_snippet(lines, idx, code)
                if snippet and snippet not in entry["snippets"]:
                    entry["snippets"].append(snippet)

    with open(DOC, encoding="utf-8") as fh:
        doc = fh.read()
    documented = set(CODE_RE.findall(doc))

    missing = sorted(set(emissions) - documented)
    lines = [
        "## Completeness annex: every issued code",
        "",
        "Generated by `scripts/dump_error_codes.py` from the production crates;",
        "regenerated as the registry changes. The workspace test",
        "`crates/emath-hir/tests/registry_complete.rs` enforces that every emitted",
        "code appears here (emitted ⊆ documented).",
        "",
        f"Emissions: **{len(emissions)} unique codes** from {len(rust_files)} rust files.",
        f"Not yet documented at generation time: **{len(missing)}**"
        + (f" ({', '.join(missing)})" if missing else "")
        + ".",
        "",
        "| Code | Emitting files | Context |",
        "|---|---|---|",
    ]
    for code in sorted(emissions):
        files = "<br>".join(sorted(emissions[code]["files"]))
        snippets = emissions[code]["snippets"][:2]
        ctx = "<br>".join(f"`{s}`" for s in snippets) if snippets else ""
        lines.append(f"| `{code}` | {files} | {ctx} |")
    lines.append("")

    annex = "\n".join(lines)

    if check_mode:
        marker = "## Completeness annex: every issued code"
        idx = doc.find(marker)
        if idx < 0 or doc[idx:] != annex:
            sys.stderr.write(
                "FAIL: ERROR_CODES.md annex is not current; regenerate with "
                "`python3 scripts/dump_error_codes.py` (splice head + annex) "
                "and re-pin contract docs (named bump).\n"
            )
            return 1
        sys.stderr.write(
            f"{len(emissions)} unique emitted codes; annex current and complete.\n"
        )
        return 0

    sys.stdout.write(annex)
    sys.stderr.write(
        f"{len(emissions)} unique emitted codes; {len(documented)} documented; "
        f"{len(missing)} newly covered by this annex.\n"
    )


if __name__ == "__main__":
    sys.exit(main())
