#!/usr/bin/env python3
"""G4 precedence boundary corpus generator (ELP gate).

The precedence-surprise sub-test has two halves:

1. Explicit precedence: every custom operator must arrive with a
   `notation <fixity> <int> "<glyph>" => <path>` declaration in the
   grammar. Operator glyphs that appear in expression productions
   (`binary_expr`, `prefix_operator`, `assignment_op`) WITHOUT a
   matching notation_decl are reported (error), because their
   precedence would be implicit parser state — undocumented surface.
   Built-in punctuation operators are listed as informational: their
   precedence lives in the parser's operator table by design.

2. Boundary corpus: for every pair of adjacent declared precedence
   tiers, emit `a <glyph_lo> a <glyph_hi> a` and the reversed order,
   pinned as a golden fixture. The corpus is deterministic (sorted),
   so the gate orders, and the fixture becomes the parse-back golden:
   a precedence change that reparenthesizes a boundary line fails the
   pairing test at code-review/parse time.

Usage:
    g4_precedence.py [--out FILE] [--check] [grammar.ebnf ...]

With `--check`: regenerate into a temp buffer and fail (exit 1) when
the on-disk fixture differs (drift gate). Without `--out`, prints the
corpus to stdout.

Stdlib only; deterministic.
"""

import argparse
import re
import sys
from collections import defaultdict


def parse_notations(text: str):
    """(fixity, precedence, glyph, target) from `notation ...` lines."""
    notations = []
    for line in text.splitlines():
        line = line.strip()
        if not line.startswith("notation"):
            continue
        rest = line[len("notation"):].strip()
        # rest: <fixity> <int> "<glyph>" => <path> [alias "<a>"]
        parts = rest.split()
        if len(parts) < 4:
            continue
        fixity = parts[0]
        try:
            precedence = int(parts[1])
        except ValueError:
            continue
        glyph = parts[2]
        if glyph.startswith('"') and glyph.endswith('"'):
            glyph = glyph[1:-1]
        else:
            continue
        target = parts[4].rstrip(",") if len(parts) > 4 and parts[3] == "=>" else ""
        notations.append((fixity, precedence, glyph, target))
    return notations


_OPERATOR_PRODUCTIONS = (
    "binary_expr",
    "prefix_operator",
    "assignment_op",
    "operator_token",
    "punctuation_operator",
)

_PROD_START = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*\s*=")


def operator_glyphs(text: str):
    """Glyphs used in operator productions: quoted literals inside the
    bodies of binary_expr / prefix_operator / assignment_op /
    operator_token / punctuation_operator. Returns (glyph, production)."""
    ops = []
    current = None
    for line in text.splitlines():
        stripped = line.strip()
        prod = next(
            (
                p
                for p in _OPERATOR_PRODUCTIONS
                if stripped.startswith(p + " ") or stripped == p
            ),
            None,
        )
        if prod:
            current = prod
            body = stripped[len(prod):]
        elif current and _PROD_START.match(stripped):
            current = None
            body = ""
        elif current:
            body = stripped
        else:
            continue
        if not body:
            continue
        for quote in ('"', "'"):
            for match in re.finditer(quote + r"([^" + quote + r"]*)" + quote, body):
                ops.append((match.group(1), current))
    return ops


def generate_corpus(notations, operators):
    """Boundary lines across adjacent precedence tiers."""
    tiers = defaultdict(list)
    for fixity, precedence, glyph, target in notations:
        tiers[precedence].append((fixity, glyph))
    if len(tiers) < 2:
        return []  # no boundaries without multiple tiers
    lines = []
    ordered = sorted(tiers)
    for lo, hi in zip(ordered, ordered[1:]):
        for glyph_lo in sorted(g for _, g in tiers[lo]):
            for glyph_hi in sorted(g for _, g in tiers[hi]):
                lines.append(f"boundary: a {glyph_lo} a {glyph_hi} a")
                lines.append(f"boundary: a {glyph_hi} a {glyph_lo} a")
    header = (
        "# G4 precedence boundary corpus (generated by scripts/g4_precedence.py; "
        "do not edit)\n"
        "# One line per adjacent declared precedence tier pair, both orders.\n"
    )
    return [header] + lines + [""]


def main(argv: list) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("grammars", nargs="+", help="EBNF grammar files")
    parser.add_argument("--out", help="fixture path to write (default stdout)")
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the on-disk fixture differs from the regenerated corpus",
    )
    args = parser.parse_args(argv)

    all_notations = []
    all_operators = []
    errors = []
    infos = []
    for path in args.grammars:
        with open(path, encoding="utf-8") as fh:
            text = fh.read()
        notations = parse_notations(text)
        operators = operator_glyphs(text)
        all_notations.extend((n[0], n[1], n[2], n[3], path) for n in notations)
        all_operators.extend((g, where, path) for g, where in operators)
        declared = {n[2] for n in notations}
        builtin = {"+", "-", "*", "/", "^", "!", "==", "!=", "<", "<=", ">", ">=",
                   "&&", "||", "==>", "<==>", "..", "..=", ":", "|", "&", "=",
                   "+=", "-=", "*=", "/=", "~~"}
        for glyph, where in operators:
            if glyph in declared or glyph in builtin:
                continue
            errors.append(
                f"{path}: operator glyph {glyph!r} in {where} has no "
                "notation_decl precedence; declare explicit precedence"
            )
        for glyph, where in operators:
            if glyph in builtin:
                infos.append(
                    f"{path}: built-in punctuation {glyph!r} in {where}; "
                    "precedence is the parser operator table"
                )

    corpus = generate_corpus(all_notations, all_operators)
    if errors:
        for message in errors:
            print(f"g4-precedence: error: {message}")
        return 1
    for message in infos:
        print(f"g4-precedence: info: {message}")

    if args.check:
        with open(args.out, encoding="utf-8") as fh:
            current = fh.read()
        regenerated = "".join(corpus)
        if current != regenerated:
            print(
                f"g4-precedence: error: {args.out} drifted from the regenerated corpus "
                f"(run `python3 scripts/g4_precedence.py {args.out and '--out ' + args.out} "
                f"{' '.join(args.grammars)}` to refresh)",
                file=sys.stderr,
            )
            return 1
        print(f"g4-precedence: {args.out} current ({len(corpus)} lines)")
        return 0

    if args.out:
        with open(args.out, "w", encoding="utf-8") as fh:
            fh.writelines(corpus)
        print(f"g4-precedence: wrote {args.out} ({len(corpus)} lines)")
    else:
        sys.stdout.writelines(corpus)
        if not corpus:
            # No custom operators yet: the shipped state is an empty
            # corpus, not an error.
            print("g4-precedence: empty corpus (no notation declarations in grammar)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
