//! Scaffold and provider metadata for `emath new`.

use super::*;

/// Relative path of the committed upstream lock file (repo layout).
pub const UPSTREAM_LOCK_REL: &str = "forks/UPSTREAM_LOCK.json";

/// Absolute lock path: crate-relative so `vendor`/`fork` work regardless of
/// the caller's working directory.
pub fn upstream_lock_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join(UPSTREAM_LOCK_REL)
}

/// Built-in provider descriptors: (id, capability, status). Status must
/// match in-tree reality: std-only native stand-ins `implemented`;
/// upstream lanes (Dew JIT/GPU, full Rumoca, Wrenfold, Franken*) always
/// `planned`.
pub const PROVIDERS: [(&str, &str, &str); 10] = [
    (
        "native.rust",
        "scalar codegen + checked constructors",
        "implemented",
    ),
    (
        "evidence.rust",
        "artifact verification + negative controls",
        "implemented",
    ),
    (
        "dew.scalar",
        "scalar strict-f64 mapping; Rust source + token backends (in-tree, std-only)",
        "implemented",
    ),
    (
        "native.causal",
        "neutral DAE plan: structural gate + native lowering",
        "implemented",
    ),
    (
        "native.euler",
        "forward-Euler simulation of causal DAE plans",
        "implemented",
    ),
    (
        "rumoca.subset-import",
        "Modelica subset scanner -> retained declarations (no upstream parse)",
        "implemented",
    ),
    (
        "phase2.expression",
        "upstream Dew engine: optimization, JIT, GPU backends",
        "planned",
    ),
    (
        "phase3.structural",
        "upstream Rumoca engine: full parse, flattening, DAE analysis",
        "planned",
    ),
    (
        "phase4.symbolic",
        "cross-engine differential corpus against a real Dew/Rumoca checkout",
        "planned",
    ),
    ("phase5.numerics", "solvers and optimization", "planned"),
];

/// `new <name> --out <dir> [--dry-run] [--force] [--json]`: deterministic project scaffold.
pub(crate) fn new_cmd(name: &str, out: &Path, dry_run: bool, force: bool, json: bool) -> CliExit {
    if !is_valid_name(name) {
        eprintln!("error: invalid package name `{name}` (E-TLT-010)");
        if json {
            print_json_diagnostics(
                "new",
                false,
                &[json_diagnostic_entry(
                    "E-TLT-010",
                    "error",
                    &format!("invalid package name `{name}`"),
                )],
            );
        }
        return EXIT_USAGE;
    }
    let main = out.join("src/main.emath");
    let manifest = out.join("emath-package.toml");
    let collision = main.exists() || manifest.exists();
    if !dry_run && collision && !force {
        eprintln!(
            "error: refusing to overwrite existing project at {} (E-TLT-011)",
            out.display()
        );
        if json {
            print_json_diagnostics(
                "new",
                false,
                &[json_diagnostic_entry(
                    "E-TLT-011",
                    "error",
                    &format!(
                        "refusing to overwrite existing project at {} (use --force to overwrite)",
                        out.display()
                    ),
                )],
            );
        }
        return EXIT_SAFETY;
    }

    let manifest_body = format!(
        "# Generated by emath new (deterministic template; edit freely).\nschema = \"emath.package\"\nname = \"{name}\"\nversion = \"0.1.0\"\nedition = \"{}\"\nmain = \"src/main.emath\"\n",
        emath_core::Edition::ALL[0]
    );
    let main_body = "emath function Greeter:\n    inputs:\n        x: Float64\n    definitions:\n        y = x\n";

    if dry_run {
        if json {
            let mut obj = JsonWriter::object();
            obj.string("command", "new");
            obj.string("status", "ok");
            obj.bool("dry_run", true);
            obj.string("name", name);
            obj.string("target_dir", &out.display().to_string());
            let planned = [
                manifest.display().to_string(),
                main.display().to_string(),
                out.join(".gitignore").display().to_string(),
            ];
            obj.strings("planned_files", &planned);
            obj.bool("will_overwrite", collision);
            println!("{}", obj.finish());
        } else {
            println!("dry-run: emath new `{name}`");
            println!("target directory: {}", out.display());
            println!("planned files:");
            println!("  - {}", manifest.display());
            println!("  - {}", main.display());
            println!("  - {}", out.join(".gitignore").display());
            if collision {
                if force {
                    println!("warning: existing files will be overwritten (--force active)");
                } else {
                    println!("warning: existing files would collide (run without --dry-run will require --force)");
                }
            }
        }
        return EXIT_OK;
    }

    if std::fs::create_dir_all(out.join("src")).is_err() {
        eprintln!("error: cannot create {}", out.display());
        return EXIT_IO;
    }
    let gitignore_body = "# Local interpretation lock (per-user, per-project).\n# Teams MAY commit .emath/meaning.lock to share one interpretation.\n.emath/meaning.lock\n";
    if let Err(error) = std::fs::create_dir_all(out.join(".emath")) {
        eprintln!(
            "error: cannot create {}: {error}",
            out.join(".emath").display()
        );
        return EXIT_IO;
    }
    if let Err(error) = std::fs::write(out.join(".gitignore"), gitignore_body) {
        eprintln!(
            "error: cannot write {}: {error}",
            out.join(".gitignore").display()
        );
        return EXIT_IO;
    }
    let result =
        std::fs::write(&manifest, &manifest_body).and_then(|()| std::fs::write(&main, main_body));
    if result.is_err() {
        eprintln!("error: cannot write scaffold under {}", out.display());
        return EXIT_IO;
    }
    if json {
        let mut obj = JsonWriter::object();
        obj.string("command", "new");
        obj.string("status", "ok");
        obj.bool("dry_run", false);
        obj.string("name", name);
        obj.string("target_dir", &out.display().to_string());
        obj.string("manifest", &manifest.display().to_string());
        obj.string("manifest_content_id", &content_id_of_str(&manifest_body).0);
        obj.string("main", &main.display().to_string());
        obj.string("main_content_id", &content_id_of_str(main_body).0);
        println!("{}", obj.finish());
    } else {
        println!(
            "created {} (content id {})",
            manifest.display(),
            content_id_of_str(&manifest_body).0
        );
        println!(
            "created {} (content id {})",
            main.display(),
            content_id_of_str(main_body).0
        );
        println!("next: emath run {} --set x=3", main.display());
    }
    EXIT_OK
}

pub(super) fn is_valid_name(name: &str) -> bool {
    let mut chars = name.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    first.is_ascii_alphabetic()
        && chars.all(|ch| ch.is_ascii_alphanumeric() || ch == '_' || ch == '-')
}
