//! Scaffold and provider metadata for `emath new`.

use super::*;

/// Relative path of the committed upstream lock file (repo layout).
pub(super) const UPSTREAM_LOCK_REL: &str = "forks/UPSTREAM_LOCK.json";

/// Absolute lock path: crate-relative so `vendor`/`fork` work regardless of
/// the caller's working directory.
pub(super) fn upstream_lock_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join(UPSTREAM_LOCK_REL)
}

/// Built-in provider descriptors: (id, capability, status). Status must
/// match in-tree reality: std-only native stand-ins `implemented`;
/// upstream lanes (Dew JIT/GPU, full Rumoca, Wrenfold, Franken*) always
/// `planned`.
pub(super) const PROVIDERS: [(&str, &str, &str); 10] = [
    (
        "native.rust",
        "scalar codegen + checked constructors",
        "implemented",
    ),
    (
        "evidence.rust",
        "artifact verification + negative controls",
        "implemented",
    ),
    (
        "dew.scalar",
        "scalar strict-f64 mapping; Rust source + token backends (in-tree, std-only)",
        "implemented",
    ),
    (
        "native.causal",
        "neutral DAE plan: structural gate + native lowering",
        "implemented",
    ),
    (
        "native.euler",
        "forward-Euler simulation of causal DAE plans",
        "implemented",
    ),
    (
        "rumoca.subset-import",
        "Modelica subset scanner -> retained declarations (no upstream parse)",
        "implemented",
    ),
    (
        "phase2.expression",
        "upstream Dew engine: optimization, JIT, GPU backends",
        "planned",
    ),
    (
        "phase3.structural",
        "upstream Rumoca engine: full parse, flattening, DAE analysis",
        "planned",
    ),
    (
        "phase4.symbolic",
        "cross-engine differential corpus against a real Dew/Rumoca checkout",
        "planned",
    ),
    ("phase5.numerics", "solvers and optimization", "planned"),
];

/// `new <name> --out <dir>`: deterministic project scaffold.
pub(crate) fn new_cmd(name: &str, out: &Path) -> CliExit {
    if !is_valid_name(name) {
        eprintln!("error: invalid package name `{name}` (E-TLT-010)");
        return EXIT_USAGE;
    }
    let main = out.join("src/main.emath");
    let manifest = out.join("emath-package.toml");
    if main.exists() || manifest.exists() {
        eprintln!(
            "error: refusing to overwrite existing project at {} (E-TLT-011)",
            out.display()
        );
        return EXIT_REFUSED;
    }
    if std::fs::create_dir_all(out.join("src")).is_err() {
        eprintln!("error: cannot create {}", out.display());
        return EXIT_USAGE;
    }
    let gitignore_body = "# Local interpretation lock (per-user, per-project).\n# Teams MAY commit .emath/meaning.lock to share one interpretation.\n.emath/meaning.lock\n";
    if let Err(error) = std::fs::create_dir_all(out.join(".emath")) {
        eprintln!(
            "error: cannot create {}: {error}",
            out.join(".emath").display()
        );
        return EXIT_USAGE;
    }
    if let Err(error) = std::fs::write(out.join(".gitignore"), gitignore_body) {
        eprintln!(
            "error: cannot write {}: {error}",
            out.join(".gitignore").display()
        );
        return EXIT_USAGE;
    }
    let manifest_body = format!(
        "# Generated by emath new (deterministic template; edit freely).\nschema = \"emath.package\"\nname = \"{name}\"\nversion = \"0.1.0\"\nedition = \"{}\"\nmain = \"src/main.emath\"\n",
        emath_core::Edition::ALL[0]
    );
    let main_body = "emath function Greeter:\n    inputs:\n        x: Float64\n    definitions:\n        y = x\n";
    let result =
        std::fs::write(&manifest, &manifest_body).and_then(|()| std::fs::write(&main, main_body));
    if result.is_err() {
        eprintln!("error: cannot write scaffold under {}", out.display());
        return EXIT_USAGE;
    }
    println!(
        "created {} (content id {})",
        manifest.display(),
        content_id_of_str(&manifest_body).0
    );
    println!(
        "created {} (content id {})",
        main.display(),
        content_id_of_str(main_body).0
    );
    println!("next: emath run {}", main.display());
    EXIT_OK
}

pub(super) fn is_valid_name(name: &str) -> bool {
    let mut chars = name.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    first.is_ascii_alphabetic()
        && chars.all(|ch| ch.is_ascii_alphanumeric() || ch == '_' || ch == '-')
}
